// Course options per stream
export const coursesByStream = {
  Science: [
    { value: 'B.Tech / B.E.', label: 'B.Tech / B.E. — Engineering' },
    { value: 'MBBS', label: 'MBBS — Medicine' },
    { value: 'B.Sc', label: 'B.Sc — Bachelor of Science' },
    { value: 'B.Pharm', label: 'B.Pharm — Pharmacy' },
    { value: 'BCA', label: 'BCA — Computer Applications' },
    { value: 'B.Arch', label: 'B.Arch — Architecture' },
    { value: 'BDS', label: 'BDS — Dental Surgery' },
    { value: 'B.Sc (Nursing)', label: 'B.Sc (Nursing)' },
    { value: 'B.Sc (Agri)', label: 'B.Sc (Agriculture)' },
  ],
  Commerce: [
    { value: 'B.Com', label: 'B.Com — Bachelor of Commerce' },
    { value: 'BBA', label: 'BBA — Business Administration' },
    { value: 'BMS', label: 'BMS — Management Studies' },
    { value: 'B.Voc', label: 'B.Voc — Vocation' },
    { value: 'CA', label: 'CA — Chartered Accountancy' },
    { value: 'B.Com (Hons)', label: 'B.Com (Hons)' },
  ],
  Arts: [
    { value: 'BA', label: 'BA — Bachelor of Arts' },
    { value: 'LLB', label: 'LLB — Law' },
    { value: 'Journalism', label: 'Journalism — Mass Communication' },
    { value: 'BFA', label: 'BFA — Fine Arts' },
    { value: 'B.Des', label: 'B.Des — Design' },
    { value: 'BSW', label: 'BSW — Social Work' },
  ],
};

// Exam configuration per course
export const examConfig = {
  'B.Tech / B.E.': {
    type: 'select',
    label: 'Engineering Entrance Exam',
    options: [
      { value: 'MHT-CET', label: 'MHT-CET' },
      { value: 'JEE Main', label: 'JEE Main' },
    ],
    scoreLabel: 'Percentile',
    placeholder: 'e.g. 88',
    suffix: 'percentile',
    max: 100,
    badge: 'Engineering entrance exam required',
  },
  'B.Arch': {
    type: 'fixed',
    fixedExam: 'NATA',
    scoreLabel: 'NATA Score',
    placeholder: 'e.g. 130',
    suffix: 'marks',
    max: 200,
    badge: 'NATA score required for Architecture',
  },
  MBBS: {
    type: 'fixed',
    fixedExam: 'NEET',
    scoreLabel: 'NEET Score',
    placeholder: 'e.g. 550',
    suffix: 'marks',
    max: 720,
    badge: 'NEET score required for MBBS admission',
  },
  BDS: {
    type: 'fixed',
    fixedExam: 'NEET',
    scoreLabel: 'NEET Score',
    placeholder: 'e.g. 450',
    suffix: 'marks',
    max: 720,
    badge: 'NEET score required for BDS admission',
  },
  'B.Pharm': {
    type: 'fixed',
    fixedExam: 'MHT-CET',
    scoreLabel: 'MHT-CET Percentile',
    placeholder: 'e.g. 75',
    suffix: 'percentile',
    max: 100,
    badge: 'MHT-CET percentile required for B.Pharm',
  },
  LLB: {
    type: 'fixed',
    fixedExam: 'MH-CET Law',
    scoreLabel: 'MH-CET Law Score',
    placeholder: 'e.g. 120',
    suffix: 'marks',
    max: 200,
    badge: 'MH-CET Law entrance score required',
  },
  'B.Des': {
    type: 'fixed',
    fixedExam: 'UCEED',
    scoreLabel: 'UCEED Score',
    placeholder: 'e.g. 150',
    suffix: 'marks',
    max: 300,
    badge: 'UCEED score required for Design',
  },
  'B.Sc': { type: 'merit' },
  'B.Sc (Nursing)': { type: 'merit' },
  'B.Sc (Agri)': { type: 'merit' },
  BCA: { type: 'merit' },
  'B.Com': { type: 'merit' },
  'B.Com (Hons)': { type: 'merit' },
  BBA: { type: 'merit' },
  BMS: { type: 'merit' },
  'B.Voc': { type: 'merit' },
  CA: { type: 'merit' },
  BA: { type: 'merit' },
  Journalism: { type: 'merit' },
  BFA: { type: 'merit' },
  BSW: { type: 'merit' },
};
